sudo: false

language: python

before_install:
  - sudo apt-get install -y rpm cpio

install: pip install tox

matrix:
  include:
  - python: "2.7"
    env: TOX_ENV=cov-travis
  - python: "3.6"
    env: TOX_ENV=py36 DEPLOY=1

script: tox -e $TOX_ENV

deploy:
  provider: pypi
  user: __token__
  password:
    secure: nbh8zk0RDhvQ5SnJUJQuXhjRtszo0Ey/8JMRoA++Wb3MwqP5TVfTE9gnzfpJVa+fqZ3/3KgXGAGmECwbYWZTGyRc3z/5khKtSfu6PN3KbsRrS4ty2AJXjgW45TeWnZse9iCKI5KniuSOLAYA8HaPLzajWFg9H27pDSP3jzOIpwB+jbvYSG9O2b7v7VTgI+CO9zJvamP6L6rM+Bq4XUXVQE2MKGvaL7WyMuz4SXqlRkV6ng5fP4QSUWI3tzkLPNgu7f3Fw8zO67ymz5bvdu/pRDWL4QQZzGW7AQKXmG/Czcxg495qJtR+mErb7FKg7zjtoSgjTN2kFrJImSF377tt2IeUMAGbyEBl1qTdQZP9k7P5M1+jhmJuOqFBdcEgsAdkeXb0+8403BBH1bKgMuGTtAa0TILOxiH/DdwHHp12GcmLPtKaWJH8NNfO9bZpZXIh995xD+9l3ZYnrghOYQ9kCHBzMaVSXZ7aAASGnrltbn7CNkK7PCF3SSnkqO1e3E5xMBdMmzzdnvlUkTvW9Rq0REXiEW2cDjveQpXVKtfj+RK0prQYXe0/4LBx28v1oIkrlUmpzFA7HUVI3W+vdNhQUyk4Eud7RTpCMxXKcEjL956FzMrnP2xLke1Fbu/fcF/1r+ZjFaopXx8IrEIx7utJ94d8Opsg6elAK9QXkzHTv/4=
  on:
    tags: true
    condition: $DEPLOY = 1
  skip_existing: true
